# Generated by Django 5.1.6 on 2025-02-14 02:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_column='tx_nome', max_length=64, verbose_name='Nome')),
                ('matricula', models.CharField(db_column='tx_matricula', max_length=6, unique=True, verbose_name='Matrícula')),
                ('cargo', models.CharField(db_column='tx_cargo', max_length=64, verbose_name='Cargo')),
                ('created_at', models.DateTimeField(db_column='dt_created', default=django.utils.timezone.now, verbose_name='Data de criação')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'db_table': 'funcionario',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(db_column='tx_identificador', max_length=64, verbose_name='Identificador')),
                ('funcionario', models.ForeignKey(blank=True, db_column='id_funcionario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cameras', to='core.funcionario', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Câmera',
                'verbose_name_plural': 'Câmeras',
                'db_table': 'camera',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('matricula', models.CharField(db_column='tx_matricula', max_length=6, unique=True, verbose_name='Matrícula')),
                ('senha', models.CharField(db_column='tx_senha', max_length=64, verbose_name='Senha')),
                ('ativo', models.BooleanField(db_column='cs_ativo', default=True, verbose_name='Ativo')),
                ('is_superuser', models.BooleanField(db_column='is_superuser', default=False, verbose_name='Superusuário')),
                ('is_staff', models.BooleanField(db_column='is_staff', default=False, verbose_name='Equipe')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('funcionario', models.OneToOneField(blank=True, db_column='id_funcionario', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='core.funcionario', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='RegistroPostura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(blank=True, db_column='dt_inicio', null=True, verbose_name='Início da má postura')),
                ('fim', models.DateTimeField(blank=True, db_column='dt_fim', null=True, verbose_name='Fim da má postura')),
                ('duracao', models.IntegerField(db_column='nr_duracao', default=0, verbose_name='Duração (segundos)')),
                ('funcionario', models.ForeignKey(db_column='id_funcionario', on_delete=django.db.models.deletion.CASCADE, to='core.funcionario', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Registro de Postura',
                'verbose_name_plural': 'Registros de Postura',
                'db_table': 'registro_postura',
                'ordering': ['-inicio'],
            },
        ),
    ]
