# Generated by Django 5.1.6 on 2025-02-12 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_nome', models.CharField(db_column='tx_nome', max_length=64, verbose_name='Nome')),
                ('tx_matricula', models.CharField(db_column='tx_matricula', max_length=6, unique=True, verbose_name='Matrícula')),
                ('tx_cargo', models.CharField(db_column='tx_cargo', max_length=64, verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'db_table': 'funcionario',
            },
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_identificador', models.CharField(db_column='tx_identificador', max_length=64, verbose_name='Identificador')),
                ('id_funcionario', models.ForeignKey(blank=True, db_column='id_funcionario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cameras', to='core.funcionario', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Câmera',
                'verbose_name_plural': 'Câmeras',
                'db_table': 'camera',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('tx_matricula', models.CharField(db_column='tx_matricula', max_length=6, unique=True, verbose_name='Matrícula')),
                ('tx_senha', models.CharField(db_column='tx_senha', max_length=64, verbose_name='Senha')),
                ('cs_ativo', models.BooleanField(db_column='cs_ativo', default=True, verbose_name='Ativo')),
                ('cs_superuser', models.BooleanField(db_column='cs_superuser', default=False, verbose_name='Superusuário')),
                ('cs_staff', models.BooleanField(db_column='cs_staff', default=False, verbose_name='Equipe')),
                ('id_funcionario', models.OneToOneField(db_column='id_funcionario', on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='core.funcionario', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='RegistroPostura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_inicio', models.DateTimeField(blank=True, db_column='dt_inicio', null=True, verbose_name='Início da má postura')),
                ('dt_fim', models.DateTimeField(blank=True, db_column='dt_fim', null=True, verbose_name='Fim da má postura')),
                ('duracao', models.IntegerField(db_column='nr_duracao', default=0, verbose_name='Duração (segundos)')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.funcionario')),
            ],
            options={
                'verbose_name': 'Registro de Postura',
                'verbose_name_plural': 'Registros de Postura',
                'db_table': 'registro_postura',
            },
        ),
    ]
