# Generated by Django 5.1.6 on 2025-02-13 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id_funcionario',
            field=models.OneToOneField(blank=True, db_column='id_funcionario', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='core.funcionario', verbose_name='Funcionário'),
        ),
    ]
