# Generated by Django 5.1.6 on 2025-02-15 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='total_alertas',
            field=models.IntegerField(db_column='nr_total_alertas', default=0, verbose_name='Total de Alertas'),
        ),
    ]
