# Generated by Django 5.1.6 on 2025-02-13 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_usuario_id_funcionario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='cs_staff',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='cs_superuser',
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_staff',
            field=models.BooleanField(db_column='is_staff', default=False, verbose_name='Equipe'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_superuser',
            field=models.BooleanField(db_column='is_superuser', default=False, verbose_name='Superusuário'),
        ),
    ]
