# Generated by Django 5.1.6 on 2025-02-17 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_funcionario_observacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(db_column='tx_cargo', max_length=64, null='', verbose_name='Cargo'),
        ),
    ]
