# Generated by Django 5.1.6 on 2025-02-17 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_funcionario_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(db_column='tx_cargo', max_length=64, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='observacoes',
            field=models.CharField(blank=True, db_column='tx_observacoes', max_length=256, null=True, verbose_name='Observações'),
        ),
    ]
