# Generated by Django 5.1.6 on 2025-02-19 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_funcionario_cargo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='identificador',
        ),
    ]
