# Generated by Django 5.1.6 on 2025-02-20 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_camera_identificador'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='matricula',
            field=models.IntegerField(blank=True, db_column='nr_matricula', max_length=6, null=True, verbose_name='Matrícula do Funcionário'),
        ),
    ]
