# Generated by Django 5.1.6 on 2025-02-20 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_camera_matricula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='matricula',
        ),
    ]
