# Generated by Django 5.1.6 on 2025-02-20 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_camera_matricula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatoriogeral',
            name='porcentagem_funcionario',
        ),
        migrations.AddField(
            model_name='relatoriogeral',
            name='indice_alertas',
            field=models.DecimalField(db_column='nr_indice_alertas', decimal_places=2, default=0.0, max_digits=6, verbose_name='Índice de Alertas'),
        ),
    ]
