# Generated by Django 5.1.6 on 2025-02-20 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_relatoriogeral_porcentagem_funcionario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatoriogeral',
            name='total_alertas',
        ),
        migrations.AddField(
            model_name='relatoriogeral',
            name='total_alertas_geral',
            field=models.IntegerField(db_column='nr_total_alertas_geral', default=0, verbose_name='Total de Alertas Geral'),
        ),
    ]
