# Generated by Django 5.1.6 on 2025-02-20 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_relatoriogeral_indice_alertas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatoriogeral',
            name='media_segundos_por_funcionario',
            field=models.DecimalField(db_column='nr_media_segundos_por_funcionario', decimal_places=2, default=0.0, max_digits=10, verbose_name='Média de segundos por funcionário'),
        ),
    ]
